export const GET_POPULAR_REQUEST = 'GET_POPULAR_REQUEST';
export const GET_POPULAR_SUCCESS = 'GET_POPULAR_SUCCESS';
export const GET_POPULAR_FAILURE = 'GET_POPULAR_FAILURE';

export const GET_TRENDING_REQUEST = 'GET_TRENDING_REQUEST';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const GET_TRENDING_FAILURE = 'GET_TRENDING_FAILURE';

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';

export const INIT_SEARCH_REQUEST = 'INIT_SEARCH_REQUEST';
export const INIT_SEARCH_SUCCESS = 'INIT_SEARCH_SUCCESS';
export const INIT_SEARCH_FAILURE = 'INIT_SEARCH_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const DETAIL_REQUEST = 'DETAIL_REQUEST';
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS';
export const DETAIL_FAILURE = 'DETAIL_FAILURE';

export const CAST_CREW_REQUEST = 'CAST_CREW_REQUEST';
export const CAST_CREW_SUCCESS = 'CAST_CREW_SUCCESS';
export const CAST_CREW_FAILURE = 'CAST_CREW_FAILURE';

export const REVIEW_REQUEST = 'REVIEW_REQUEST';
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS';
export const REVIEW_FAILURE = 'REVIEW_FAILURE';

export const VIDEO_REQUEST = 'VIDEO_REQUEST';
export const VIDEO_SUCCESS = 'VIDEO_SUCCESS';
export const VIDEO_FAILURE = 'VIDEO_FAILURE';

export const IMAGES_REQUEST = 'IMAGES_REQUEST';
export const IMAGES_SUCCESS = 'IMAGES_SUCCESS';
export const IMAGES_FAILURE = 'IMAGES_FAILURE';

export const RECOMMENDATIONS_REQUEST = 'RECOMMENDATIONS_REQUEST';
export const RECOMMENDATIONS_SUCCESS = 'RECOMMENDATIONS_SUCCESS';
export const RECOMMENDATIONS_FAILURE = 'RECOMMENDATIONS_FAILURE';

export const GENRES_REQUEST = 'GENRES_REQUEST';
export const GENRES_SUCCESS = 'GENRES_SUCCESS';
export const GENRES_FAILURE = 'GENRES_FAILURE';

export const CERTIFICATIONS_REQUEST = 'CERTIFICATIONS_REQUEST';
export const CERTIFICATIONS_SUCCESS = 'CERTIFICATIONS_SUCCESS';
export const CERTIFICATIONS_FAILURE = 'CERTIFICATIONS_FAILURE';

export const LANGUAGES_REQUEST = 'LANGUAGES_REQUEST';
export const LANGUAGES_SUCCESS = 'LANGUAGES_SUCCESS';
export const LANGUAGES_FAILURE = 'LANGUAGES_FAILURE';

export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST';
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS';
export const COUNTRIES_FAILURE = 'COUNTRIES_FAILURE';

export const WATCH_REGIONS_REQUEST = 'WATCH_REGIONS_REQUEST';
export const WATCH_REGIONS_SUCCESS = 'WATCH_REGIONS_SUCCESS';
export const WATCH_REGIONS_FAILURE = 'WATCH_REGIONS_FAILURE';

export const PERSON_CREDITS_REQUEST = 'PERSON_CREDITS_REQUEST';
export const PERSON_CREDITS_SUCCESS = 'PERSON_CREDITS_SUCCESS';
export const PERSON_CREDITS_FAILURE = 'PERSON_CREDITS_FAILURE';

export const EXTERNALS_REQUEST = 'EXTERNALS_REQUEST';
export const EXTERNALS_SUCCESS = 'EXTERNALS_SUCCESS';
export const EXTERNALS_FAILURE = 'EXTERNALS_FAILURE';

export const KEYWORDS_REQUEST = 'KEYWORDS_REQUEST';
export const KEYWORDS_SUCCESS = 'KEYWORDS_SUCCESS';
export const KEYWORDS_FAILURE = 'KEYWORDS_FAILURE';

export const SEARCH_BY_KEYWORD_REQUEST = 'SEARCH_BY_KEYWORD_REQUEST';
export const SEARCH_BY_KEYWORD_SUCCESS = 'SEARCH_BY_KEYWORD_SUCCESS';
export const SEARCH_BY_KEYWORD_FAILURE = 'SEARCH_BY_KEYWORD_FAILURE';

export const DETAIL_SEASON_REQUEST = 'DETAIL_SEASON_REQUEST';
export const DETAIL_SEASON_SUCCESS = 'DETAIL_SEASON_SUCCESS';
export const DETAIL_SEASON_FAILURE = 'DETAIL_SEASON_FAILURE';

export const ALTERNATIVE_TITLES_REQUEST = 'ALTERNATIVE_TITLES_REQUEST';
export const ALTERNATIVE_TITLES_SUCCESS = 'ALTERNATIVE_TITLES_SUCCESS';
export const ALTERNATIVE_TITLES_FAILURE = 'ALTERNATIVE_TITLES_FAILURE';

export const RELEASES_DATE_REQUEST = 'RELEASES_DATE_REQUEST';
export const RELEASES_DATE_SUCCESS = 'RELEASES_DATE_SUCCESS';
export const RELEASES_DATE_FAILURE = 'RELEASES_DATE_FAILURE';
